### ISSUE TITLE
bad interpretation of enum schemas

### ISSUE THREAD

**Issue by yoyos** [oatpp/oatpp-swagger#81]
An openapi using this schema 
```
schemas:
    CaptureMode:
      type: string
      enum:
        - idle
        - snapshot
        - freerun
        - calibration
```

is not interpreted correctly when by the oatpp-swagger ui and it makes the call crash without additional double quotes :

![image](https://github.com/oatpp/oatpp-swagger/assets/1993859/01b49f37-7347-4c4f-9edd-3be0d99643c5)

The same openapi spec renders doubles quotes correctly on https://editor.swagger.io:

![image](https://github.com/oatpp/oatpp-swagger/assets/1993859/eeb7f3af-df56-4f63-8666-c6f7ed7d3543)
